[package]
name = "swapper-package"
version = "0.1.0"
description = "Swapper package"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "swapper_package"

[features]
library = []

[dependencies]
anchor-lang = { version = "0.28.0", features = ["init-if-needed"] }
anchor-spl = "0.28.0"
solana-program = "1.16"
common = { path = "../common", version = "0.1.0", features = ["library"]}