[package]
name = "common"
version = "0.1.0"
description = "Common package"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "common"

[features]
library = []

[dependencies]
anchor-lang = { version="0.28.0", features=["init-if-needed"] }
anchor-spl = "0.28.0"
# solana-program = "1.16"
borsh = "1.4.0"
uint = { version = "0.9.1", default-features = false }

# strategy-mock ={ path = "../../programs/strategy-mock",version = "0.1.0",features = ["cpi"]}
